export const parameters = [
  {
    id: "param1",
    param: "Parameter 1",
    unit: "kWh",
    value: 123.45,
    status: "Not Verified",
  },
  {
    id: "param2",
    param: "Parameter 2",
    unit: "kW",
    value: 67.89,
    status: "Not Verified",
  },
  {
    id: "param3",
    param: "Parameter 3",
    unit: "V",
    value: 230,
    status: "Not Verified",
  },
  {
    id: "param4",
    param: "Parameter 4",
    unit: "A",
    value: 10.5,
    status: "Not Verified",
  },
  {
    id: "param5",
    param: "Parameter 5",
    unit: "Hz",
    value: 50,
    status: "Not Verified",
  },
  {
    id: "param6",
    param: "Parameter 6",
    unit: "kWh",
    value: 200.75,
    status: "Not Verified",
  },
    {
        id: "param7",
        param: "Parameter 7",
        unit: "kW",
        value: 150.25,
        status: "Not Verified",
    },
    {
        id: "param8",
        param: "Parameter 8",
        unit: "V",
        value: 400,
        status: "Not Verified",
    },
    {
        id: "param9",
        param: "Parameter 9",
        unit: "A",
        value: 20.0,
        status: "Not Verified",
    },
    {
        id: "param10",
        param: "Parameter 10",
        unit: "Hz",
        value: 60,
        status: "Not Verified",
    },
    {
        id: "param11",
        param: "Parameter 11",
        unit: "kWh",
        value: 300.50,
        status: "Not Verified",
    },
    {
        id: "param12",
        param: "Parameter 12",
        unit: "kW",
        value: 175.75,
        status: "Not Verified",
    },
    {
        id: "param13",
        param: "Parameter 13",
        unit: "V",
        value: 380,
        status: "Not Verified",
    },
    {
        id: "param14",
        param: "Parameter 14",
        unit: "A",
        value: 15.5,
        status: "Not Verified",
    },
    {
        id: "param15",
        param: "Parameter 15",
        unit: "Hz",
        value: 55,
        status: "Not Verified",
    },
];
